version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      # Login to AWS ECR
      echo Logging in to Amazon ECR...
      aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 752023216802.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      # Build the Docker image
      echo Building the Docker image...
      docker build -t aspnet-core-dotnet-core .

      # Tag the Docker image
      echo Tagging the Docker image...
      docker tag aspnet-core-dotnet-core:latest 752023216802.dkr.ecr.us-east-1.amazonaws.com/dotnet:latest
  post_build:
    commands:
      # Push the Docker image to ECR
      echo Pushing the Docker image...
      docker push 752023216802.dkr.ecr.us-east-1.amazonaws.com/dotnet:latest

      # # Deploy the Docker container to EC2 (update with your deployment commands)
      # echo Deploying to EC2...
      # # Use SSH to deploy the container (ensure SSH access is set up)
      # ssh -o StrictHostKeyChecking=no -i /path/to/your/key.pem ec2-user@your-ec2-instance-ip "docker pull your-account-id.dkr.ecr.your-region.amazonaws.com/aspnet-core-dotnet-core:latest && docker stop aspnet-core-dotnet-core || true && docker rm aspnet-core-dotnet-core || true && docker run -d -p 8080:80 --name aspnet-core-dotnet-core your-account-id.dkr.ecr.your-region.amazonaws.com/aspnet-core-dotnet-core:latest"

artifacts:
  files:
    - '**/*'
